"""
Core types for kyo-mcp, strictly enforcing the Open Knowledge Format (OKF) v0.2 standard.
Aligns exactly with the source-of-truth Markdown structure defined by Google's knowledge-catalog SPEC.md.
"""

from typing import Any, Dict, List, Optional

from kyo_mcp.ontology import OntologyAnnotation
from pydantic import BaseModel


class Actor(BaseModel):
    """Represents an actor string: /agent_name, human:name, or process:name"""

    value: str


class GeneratedInfo(BaseModel):
    """§5.2 `generated`: Records how the current content was produced."""

    by: str  # e.g., "process:kyo-mcp"
    at: str  # ISO 8601 timestamp


class VerificationEntry(BaseModel):
    """§5.2 `verified`: List of individual verification events."""

    by: str
    at: str


class ProvenanceSource(BaseModel):
    """§5.1 `sources`: A material a concept derives from."""

    id: Optional[str] = None
    resource: str
    title: Optional[str] = None
    author: Optional[str] = None


class OKFConcept(BaseModel):
    """The standard conceptual structure for an OKF v0.2 bundle file."""

    # Required fields
    id: Optional[str] = None
    type: str

    # Recommended fields
    title: Optional[str] = None
    description: Optional[str] = None

    # Resource and Tags
    resource: Optional[Dict[str, str]] = None  # {"uri": "..."}
    tags: List[str] = []

    # Lifecycle and Trust
    status: str = "stable"  # draft | stable | deprecated
    generated: Optional[GeneratedInfo] = None
    verified: Optional[List[VerificationEntry]] = None
    sources: List[ProvenanceSource] = []
    metadata: Dict[str, Any] = {}

    # Ontology annotations (lightweight, optional)
    ontology: Optional[OntologyAnnotation] = None

    def to_markdown(self) -> str:
        """Serializes the concept into an OKF-compliant Markdown bundle file."""
        import yaml

        content = "---\n"

        # Required: type
        frontmatter: Dict[str, Any] = {"type": self.type}

        # Recommended
        if self.title:
            frontmatter["title"] = self.title
        if self.description:
            frontmatter["description"] = self.description
        if self.resource:
            frontmatter["resource"] = self.resource["uri"]
        if self.tags:
            frontmatter["tags"] = self.tags

        # Lifecycle / Trust (strict v0.2 structures)
        if self.status and self.status != "stable":
            frontmatter["status"] = self.status

        if self.generated:
            frontmatter["generated"] = {
                "by": self.generated.by,
                "at": self.generated.at,
            }

        content += yaml.dump(frontmatter, default_flow_style=False) + "---\n"

        # Body (placeholder for now)
        generated_by = self.generated.by if self.generated else "unknown"
        content += f"# {self.title or 'Untitled'}\n\nGenerated by {generated_by}.\n"

        return content
